### ISSUE TITLE
Exomizer dependency?

### ISSUE THREAD

**Issue by josx** [ricardoquesada/c64-the-muni-race#1]
Trying to compile it get 

```
make: exomizer: No se encontró el programa
make: *** [dist] Error 127
```

Seems to need http://hem.bredband.net/magli143/exo/ maybe it is better to include it in readme.

**Comment by ricardoquesada** [comment]
Actually exomizer is not needed to run the game.
Just do:
`$ make test` and exomizer won't be used.

I'll update the README though. thanks.

**Comment by ricardoquesada** [comment]
fixed: https://github.com/ricardoquesada/c64-the-muni-race/commit/9d39c1a0da6946a5d7f4375684e68e42cc708fc2

**Comment by josx** [comment]
perfect!
