### ISSUE TITLE
Install vice on debian/ubuntu 

### ISSUE THREAD

**Issue by josx** [ricardoquesada/c64-the-muni-race#2]
Maybe to include it in readme or just for the record.
If you install Vice in Debian  `$ apt-get install vice` for copyright issues you dont get ROMs.

To make it work here there is  a good tutorial 
http://iseborn.eu/wiki/index.php?title=Ubuntu/Install_and_set_up_VICE

**Comment by ricardoquesada** [comment]
thanks. fixed.
